# Generated by Django 3.0.4 on 2020-05-04 13:38

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_implementations", "0001_initial"),
        ("cases", "0002_remove_case_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "responses",
                    django_mysql.models.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "ai_implementations",
                    models.ManyToManyField(
                        related_name="_benchmarkingsession_ai_implementations_+",
                        to="ai_implementations.AIImplementation",
                    ),
                ),
                (
                    "case_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.CaseSet",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
