# Generated by Django 3.0.4 on 2020-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benchmarking_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchmarkingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("intermediate", "Intermediate"),
                    ("finished", "Finished"),
                ],
                default="created",
                max_length=50,
            ),
        ),
    ]
